server:
  port: 6000

saas:
  oil:
    endpoint:
      #url: http://10.60.130.32:6000
      url: http://localhost:6000
  weather:
    endpoint:
      #url: http://10.60.130.103:7000
      url: http://localhost:7000

logging:
  level:
    root: debug