server:
  port: 6000

saas:
  oil:
    endpoint:
      #url: http://10.60.130.32:8000
      url: http://localhost:8000
  weather:
    endpoint:
      #url: http://10.60.130.103:7000
      url: http://localhost:8000

logging:
  level:
    root: debug