name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "dev_jaeho" ]
  pull_request:
    branches: [ "dev_jaeho" ]

env:
  APP_NAME: saas-bff
  AWS_REGION: ap-northeast-2
  AWS_ROLE: arn:aws:iam::794187215716:role/devops_saas_github_oidc

jobs:

  aws-oidc-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set AWS OIDC ROLE
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


