name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "dev_jaeho" ]
  pull_request:
    branches: [ "dev_jaeho" ]

permissions:
  id-token: write

env:
  APP_NAME: saas-bff
  BRANCH_NAME: dev_jaeho

jobs:

  aws-oidc-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0

      - name: Grant execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Set AWS OIDC ROLE
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: ecrRoleSession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build . -t 794187215716.dkr.ecr.ap-northeast-2.amazonaws.com/${{ env.APP_NAME }}:release-${{ env.BRANCH_NAME }}-${{ github.sha }} --build-arg VERSION=${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: docker push 794187215716.dkr.ecr.ap-northeast-2.amazonaws.com/${{ env.APP_NAME }}:release-${{ env.BRANCH_NAME }}-${{ github.sha }}






