name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "dev_jaeho" ]
  pull_request:
    branches: [ "dev_jaeho" ]

env:
  APP_NAME: saas-bff

jobs:
  build-and-image-create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0

      - name: Grant execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Extract branch name
        id: vars
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build Docker image
        run: |
          docker build . -t ${{ secrets.JAEHO_DOCKER_NAME }}/${{ env.APP_NAME }}:release-${{ steps.vars.outputs.branch }}-${{ github.sha }} --build-arg VERSION=${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.JAEHO_DOCKER_ID }}
          password: ${{ secrets.JAEHO_DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.JAEHO_DOCKER_NAME }}/${{ env.APP_NAME }}:release-${{ steps.vars.outputs.branch }}-${{ github.sha }}


  git-remote-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update remote Kubernetes Manifest
        env:
          GITHUB_TOKEN: ${{ secrets.JAEHO_PAT_TOKEN }}
          repository: 'saas-in-the-well/saas-kubernetes'
        run: |
          git checkout dev_jaeho
          git pull --rebase origin dev_jaeho
          
          sed -i 's|^.*image:.*|          image: ${{ secrets.JAEHO_DOCKER_NAME }}/${{ env.APP_NAME }}:release-${{ steps.vars.outputs.branch }}-${{ github.sha }}|' kube/jaeho/${{ env.APP_NAME }}.yaml
          
          git config user.email ${{ secrets.JAEHO_GITHUB_EMAIL }}
          git config user.name "GitHub Actions"
          git add kube/jaeho/${{ env.APP_NAME }}.yaml
          git commit -m "Update image tag in Kubernetes manifest"
          git push origin dev_jaeho